title: Interlace.Works 
email: andy@r210.com 
description: >- 
  Celtic knots and mazes.
baseurl: "interlace" 
url:     "" 
twitter_username: TBD
github_username:  TBD

theme: minima
plugins:
  - jekyll-feed

